logger: Explicit to_s conversion in conditional
It seems that Ruby 3.2 does not support implicit string conversions
when done in regex match operator. Apparently somewhere we pass
ServerObjects directly when printing log lines.

Full stacktrace:
homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/logger.rb:105:in `block in log': undefined method `=~' for #<Capistrano::ServerDefinition:0x00007f016dbc9290 @user=nil, @host="<randomhostnamehere>", @port=nil, @options={}, @hash=2160641792182834451> (NoMethodError)
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/logger.rb:103:in `each'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/logger.rb:103:in `log'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/logger.rb:158:in `trace'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/command.rb:214:in `block (4 levels) in open_channels'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/command.rb:270:in `block in request_pty_if_necessary'
	from homedir/bundle/ruby/3.2.0/gems/net-ssh-5.2.0/lib/net/ssh/connection/channel.rb:627:in `do_success'
	from homedir/bundle/ruby/3.2.0/gems/net-ssh-5.2.0/lib/net/ssh/connection/session.rb:687:in `channel_success'
	from homedir/bundle/ruby/3.2.0/gems/net-ssh-5.2.0/lib/net/ssh/connection/session.rb:549:in `dispatch_incoming_packets'
	from homedir/bundle/ruby/3.2.0/gems/net-ssh-5.2.0/lib/net/ssh/connection/session.rb:249:in `ev_preprocess'
	from homedir/bundle/ruby/3.2.0/gems/net-ssh-5.2.0/lib/net/ssh/connection/session.rb:241:in `preprocess'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/processable.rb:17:in `block in process_iteration'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/processable.rb:45:in `block in ensure_each_session'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/processable.rb:43:in `each'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/processable.rb:43:in `ensure_each_session'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/processable.rb:17:in `process_iteration'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/command.rb:171:in `block (2 levels) in process!'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/command.rb:170:in `loop'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/command.rb:170:in `block in process!'
	from /usr/local/lib/ruby/3.2.0/benchmark.rb:311:in `realtime'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/command.rb:169:in `process!'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/command.rb:140:in `process'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/configuration/actions/invocation.rb:198:in `block in run_tree'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/configuration/connections.rb:205:in `block in execute_on_servers'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/configuration/connections.rb:193:in `each'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/configuration/connections.rb:193:in `each_slice'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/configuration/connections.rb:193:in `execute_on_servers'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/configuration/actions/invocation.rb:196:in `run_tree'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/configuration/actions/invocation.rb:155:in `run'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/configuration/namespaces.rb:191:in `method_missing'
	from ./config/deploy.rb:204:in `block (2 levels) in load'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/configuration/execution.rb:138:in `instance_eval'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/configuration/execution.rb:138:in `invoke_task_directly'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/configuration/callbacks.rb:25:in `invoke_task_directly_with_callbacks'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/configuration/execution.rb:89:in `execute_task'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/callback.rb:38:in `call'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/configuration/callbacks.rb:141:in `block in trigger'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/configuration/callbacks.rb:141:in `each'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/configuration/callbacks.rb:141:in `trigger'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/configuration/callbacks.rb:23:in `invoke_task_directly_with_callbacks'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/configuration/execution.rb:89:in `execute_task'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/configuration/namespaces.rb:191:in `method_missing'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/configuration/namespaces.rb:110:in `block in define_task'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/recipes/deploy.rb:234:in `block (3 levels) in load'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/configuration/execution.rb:56:in `transaction'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/configuration/namespaces.rb:191:in `method_missing'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/recipes/deploy.rb:233:in `block (2 levels) in load'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/configuration/execution.rb:138:in `instance_eval'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/configuration/execution.rb:138:in `invoke_task_directly'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/configuration/callbacks.rb:25:in `invoke_task_directly_with_callbacks'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/configuration/execution.rb:89:in `execute_task'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/configuration/namespaces.rb:191:in `method_missing'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/configuration/namespaces.rb:110:in `block in define_task'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/recipes/deploy.rb:201:in `block (2 levels) in load'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/configuration/execution.rb:138:in `instance_eval'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/configuration/execution.rb:138:in `invoke_task_directly'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/configuration/callbacks.rb:25:in `invoke_task_directly_with_callbacks'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/configuration/execution.rb:89:in `execute_task'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/cli/execute.rb:46:in `block in execute_requested_actions'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/cli/execute.rb:45:in `each'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/cli/execute.rb:45:in `execute_requested_actions'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/cli/help.rb:19:in `execute_requested_actions_with_help'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/cli/execute.rb:34:in `execute!'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/lib/capistrano/cli/execute.rb:14:in `execute'
	from homedir/bundle/ruby/3.2.0/gems/capistrano-2.15.9/bin/cap:4:in `<top (required)>'
	from homedir/bundle/ruby/3.2.0/bin/cap:25:in `load'
	from homedir/bundle/ruby/3.2.0/bin/cap:25:in `<top (required)>'
	from /usr/local/bundle/gems/bundler-2.4.6/lib/bundler/cli/exec.rb:58:in `load'
	from /usr/local/bundle/gems/bundler-2.4.6/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/local/bundle/gems/bundler-2.4.6/lib/bundler/cli/exec.rb:23:in `run'
	from /usr/local/bundle/gems/bundler-2.4.6/lib/bundler/cli.rb:491:in `exec'
	from /usr/local/bundle/gems/bundler-2.4.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/bundler-2.4.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/bundler-2.4.6/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/gems/bundler-2.4.6/lib/bundler/cli.rb:34:in `dispatch'
	from /usr/local/bundle/gems/bundler-2.4.6/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /usr/local/bundle/gems/bundler-2.4.6/lib/bundler/cli.rb:28:in `start'
	from /usr/local/bundle/gems/bundler-2.4.6/exe/bundle:45:in `block in <top (required)>'
	from /usr/local/bundle/gems/bundler-2.4.6/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /usr/local/bundle/gems/bundler-2.4.6/exe/bundle:33:in `<top (required)>'
	from /usr/local/bundle/bin/bundle:25:in `load'
	from /usr/local/bundle/bin/bundle:25:in `<main>'